---
- name: Instala nginx
  apt:
    name: nginx
    state: present
  notify: "restart nginx"
  register: nginx

- debug:
    msg: "{{ nginx }}"

- name: Revisa proceso
  shell: "ps xua| grep nginx | grep -v grep"
  register: proceso

- debug:
    msg: "{{ proceso }}"

- name: Cambia index.html
  template:
    src: index.j2
    dest: /var/www/html/index.nginx-debian.html
    mode: 0755
  register: index

- debug:
    msg: "{{index}}"
