---
- hosts: localhost
  connection: local

  roles:
    - custom

  tasks:
    - name: Cambia index.html
      template:
        src: index.j2
        dest: /var/www/html/index.nginx-debian.html
        mode: 0755
      register: index

    - debug:
        msg: "{{index}}"
